### ISSUE TITLE
Better feedback on error

### ISSUE THREAD

**Issue by tjoskar** [amlinger/homebridge-telldus-tdtool#18]
First of all nice plugin!

I tried out the plugin but got the error message "TypeError: Cannot read property 'characteristics' of undefined" until I started to debug the plugin and found this line: https://github.com/amlinger/homebridge-telldus-tdtool/blob/c4ee825be979089a7a9914ae423d2a7d29ad8779/src/lib/telldus-accessory.js#L139 and that `homebridgeModel` will be `undefined` if the model was something else then 'selflearning-switch', 'codeswitch' or 'selflearning-dimmer'.

Wouldn't it be great if an error with a better error message was thrown instead. Like:

``` javascript
if (!homebridgeModel) {
    throw new Error(`The device model must be 'selflearning-switch', 'codeswitch' or 'selflearning-dimmer'`);
}
```

**Comment by amlinger** [comment]
I agree, that's definitely a bug, and some sort of check should be in place. However the bigger issue to me is that the current implementation of the `TelldusAccessory` class is not sustainable, and as I'm adding support for thermometer sensors (see #17), refactoring will be done and that will address this issue as well. 

Thanks for reporting!
