### ISSUE TITLE
Hangs on unsupported sensor types

### ISSUE THREAD

**Issue by pkempe** [amlinger/homebridge-telldus-tdtool#24]
I have a couple of Oregon sensors, namely one combined temp/humidity sensor and a rain sensor. I get the valid complaints during init of homebridge:
    `[Telldus-TD-Tool] Model "1A2D" is not supported (...)`
    `[Telldus-TD-Tool] Model "2914" is not supported (...)`

However, the init never finishes, leaving the homebridge in an unusable state because of this. 1A2D I was going to implement support for and do a PR myself, I thought, but implementing support for a fancy rain sensor just to get the temp sensors working is a bit above my current capacity.

As a workaround, could this plugin just skip the sensors of unsupported types?

FWIW, here's the tdtool output for my specific sensors:
    `type=sensor    protocol=oregon model=1A2D  id=238  temperature=19.7    humidity=46 time=2016-10-01 21:04:50    age=62`
    `type=sensor    protocol=oregon model=2914  id=19   rainrate=0.0    raintotal=713.1`

**Comment by amlinger** [comment]
All right, that should not be a problem though, it should not halt because a sensor was not found, thats what [this filter](https://github.com/amlinger/homebridge-telldus-tdtool/blob/master/src/index.js#L64-L66) takes care of. Would you mind sharing a bit more of your log?

**Comment by pkempe** [comment]
Sure, here's the full log:

Oct  1 14:02:30 rpi systemd[1]: Starting Node.js HomeKit Server...
Oct  1 14:02:30 rpi systemd[1]: Started Node.js HomeKit Server.
Oct  1 14:02:31 rpi dhcpcd[387]: eth0: Router Advertisement from fe80::cad7
:19ff:fe37:9d7d
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* The program 'node' u
ses the Apple Bonjour compatibility layer of Avahi.
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* The program 'node' uses th
e Apple Bonjour compatibility layer of Avahi.
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* Please fix your applicatio
n to use the native API of Avahi!
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* For more information see <
http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* The program 'node' called 
'DNSServiceRegister()' which is not supported (or only supported partially)
 in the Apple Bonjour compatibility layer of Avahi.
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* Please fix your applicatio
n to use the native API of Avahi!
Oct  1 14:02:34 rpi node[19615]: **\* WARNING **\* For more information see <
http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* Please fix your appl
ication to use the native API of Avahi!
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* For more information
 see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* The program 'node' c
alled 'DNSServiceRegister()' which is not supported (or only supported part
ially) in the Apple Bonjour compatibility layer of Avahi.
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* Please fix your appl
ication to use the native API of Avahi!
Oct  1 14:02:34 rpi homebridge[19615]: **\* WARNING **\* For more information
 see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegist
er>
Oct  1 14:02:39 rpi homebridge[19615]: [2016-10-01 14:02:39] Loaded plugin:
 homebridge-telldus-tdtool
Oct  1 14:02:39 rpi homebridge[19615]: [2016-10-01 14:02:39] Registering pl
atform 'homebridge-telldus-tdtool.Telldus-TD-Tool'
Oct  1 14:02:39 rpi homebridge[19615]: [2016-10-01 14:02:39] ---
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] Loaded plugin:
 homebridge-webehome
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] Registering pl
atform 'homebridge-webehome.WeBeHome'
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] ---
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] Loaded config.
json with 0 accessories and 1 platforms.
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] ---
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] Loading 1 plat
forms...
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] [Telldus-TD-To
ol] Initializing Telldus-TD-Tool platform...
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] [Telldus-TD-To
ol] Loading devices...
Oct  1 14:02:44 rpi homebridge[19615]: [2016-10-01 14:02:44] Loading 0 acce
ssories...
Oct  1 14:02:46 rpi homebridge[19615]: [2016-10-01 14:02:46] [Telldus-TD-To
ol] Found 3 items of type "device".
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Found 15 items of type "sensor".
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Model "1A2D" is not supported, try [selflearning-switch, codeswitch, se
lflearning-dimmer, humidity, temperature, temperaturehumidity]. If you stil
lhave not found what you're looking for, submit a pull at https://github.co
m/amlinger/homebridge-telldus-tdtool
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Model "2914" is not supported, try [selflearning-switch, codeswitch, se
lflearning-dimmer, humidity, temperature, temperaturehumidity]. If you stil
lhave not found what you're looking for, submit a pull at https://github.co
m/amlinger/homebridge-telldus-tdtool
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Model "2914" is not supported, try [selflearning-switch, codeswitch, se
lflearning-dimmer, humidity, temperature, temperaturehumidity]. If you stil
lhave not found what you're looking for, submit a pull at https://github.co
m/amlinger/homebridge-telldus-tdtool
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Initializing platform accessory 'Utomhusbrytare'...
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] [Utomhusbrytare]: getServices called
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Initializing platform accessory 'Brytare 1'...
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] [Brytare 1]: getServices called
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Initializing platform accessory 'Brytare 2'...
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] [Brytare 2]: getServices called
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Initializing platform accessory 'Thermometer'...
Oct  1 14:02:47 rpi homebridge[19615]: [2016-10-01 14:02:47] [Telldus-TD-To
ol] Initializing platform accessory 'Thermometer'...

**Comment by pkempe** [comment]
After that, nothing happens and all HomeKit apps reports 'no response' for all accessories connected through homebridge.

**Comment by pkempe** [comment]
I should point out that I have no issues when installing from npm, i.e. 1.0.3. Ostensibly, there could be something else that's changed after that release that causes this.

**Comment by amlinger** [comment]
It seems to get farther than just not recognizing your sensor models, I don't think that is the issue. I believe that it has something to do with initalizing your second Thermometer.

I haven't deployed the sensor-support to `npm` yet, as I haven't tested it thoroughly myself yet. That is probably why that is working for you, since that version simply does not care about sensors.

I'll do a bit of digging to see if I can find the culprit of this.

**Comment by jannylund** [comment]
I think this was fixed by https://github.com/amlinger/homebridge-telldus-tdtool/pull/25 . The log looks identical to my original issue. (although I suppose there may be an underlying problem showing up afterward with the rainsensor).

**Comment by pkempe** [comment]
Just applied the as of now current build, and can confirm that I get past the previous hang and the sensors are listed properly.
