### ISSUE TITLE
State changed from outside tdtool is not shown correctly in homekit.

### ISSUE THREAD

**Issue by jannylund** [amlinger/homebridge-telldus-tdtool#34]
If you use devices in telldus, and change the devices state from outside of homekit, the correct state is not presented in homekit. 

For example: turn on a device through homekit. Turn it off with direct remote control. Homekit will still show it as on, but `tdtool --list` will show it correctly as off.

**Comment by jannylund** [comment]
Actually, this seem to work correctly now so I can't reproduce it.

 Not sure why it failed before. I suggest however to add logging on the request + state as well as a check if the device is not existing. (long shot, but it could actually happen if telldus.conf is modified and telldusd restarted).

**Comment by amlinger** [comment]
Yes, this should definitely be in place. I agree that we need logging for the edge cases when a device disappears, and currently many assumptions are made about devices always being present once discovered.

**Comment by jannylund** [comment]
A week later and I have not been able to reproduce. I think the issue is that sometimes Elgato Eve app / Homekit app does not refresh unless you "force" it to.
