### ISSUE TITLE
Issue with TelldusDimmer, light sometimes goes to 100%

### ISSUE THREAD

**Issue by andlier** [amlinger/homebridge-telldus-tdtool#38]
With a Telldus Dimmer, the light sometimes goes to 100% and stays there, sometimes it goes first to 100% then down to the set dimlevel. 

Seems the issue is related to class TelldusDimmer extending TelldusSwitch in telldus-accessory.js. When dimlevel is set from homekit on apple-device, both setState (in TelldusSwitch) and setDimLevel is called. (for some reason, in the homebridge log, these functions are not called in the same order all the time, so sometimes dimlevel is set first, then tdtool --on/--off is called, and some times the other way around. 

The correct behavior for a Telldus Dimmer should be to only call "tdtool --off" if dimlevel == 0 or off-command received. 
In every other case "tdtool --dimlevel --dim " -command should be called with either the new dimlevel received or the last set dimlevel if only --on command received.  Never call "tdtool --on" for a telldus dimmer, it messes up the state, (overrides any previously set dimlevel).

I'd be happy to discuss a fix, but I don't know enough javascript to implement myself.

**Comment by andlier** [comment]
More careful debugging reveals that this seems to be an issue that occurs because on/off and brightness commands are mixed together by the native apple homekit in iOS 10.  it behaves more correct with a third party homekit app in iOS 9 where brightness control and on/off control are separated as two distinct functions.

**Comment by amlinger** [comment]
There seems to be something to this, I agree. This would introduce a bit more state into the sensors than is currently there, but I don't think that it would be a problem.

It is a matter of interpretation, the current one is that `ON` means full light, and `OFF` means 0, with no memory of what the previous state was. This is not necessarily the correct one, and I believe what you expected to happen might be more appropriate.

**Comment by andlier** [comment]
Yes, the apple homekit used from the control-center pull-up menu on iOS 10 doesn't remember the state of a dimmed switch when it is switched off, it is however calling the getDimlevel even when the switch is set off, I assume that is so it can send the correct dimlevel when turned on again. But it will always go back to 100% as it is now.

clicking a dimmable accessory from the control-center results in both setState and setDimlevel getting called in random order. So sometimes the light goes to 100% some times it goes to the correct dimlevel. 

Same happens when adjusting the dimlevel from the control-center. 

This works a bit better when using 3rd party apps as mentioned in previous comment, as they can separate out the dimming and switching commands. 

I'd be happy if there is an intermediate solution without the state retention that can work. maybe just have an option to ignore the setState function and only call setDimlevel for dimmable accessories when any other value than 0 (off) is sent. Although it might be that only setState is called when just turning on the light...

**Comment by andlier** [comment]
Added a pull request with a fix for this (maybe a quick-fix, but it works for my usecase at least)  Thanks for the prompt comments and feedback here.

**Comment by amlinger** [comment]
Great, #40 is the link to it for reference.

**Comment by amlinger** [comment]
Forgot to add closing comment in the PR #41, closing from here instead.
