### ISSUE TITLE
Telldusd looping through some of the devices - Siri "timeout"

### ISSUE THREAD

**Issue by larspetter** [amlinger/homebridge-telldus-tdtool#39]
Having issues with Siri timing out on turning on/off Telldus devices. Seeing that after all devices turned on, the Tellstick keeps flashing blue for 30-60 secs more.

Looking into /var/log/messages I see that Telldusd is looping through some of the devices: (6 and 10). Any ideas what might cause that behavior?

Nov  9 16:10:52 raspberrypi telldusd: Execute a TellStick Action for device 3
Nov  9 16:10:53 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:10:53 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:10:55 raspberrypi telldusd: Execute a TellStick Action for device 2
Nov  9 16:10:55 raspberrypi telldusd: Execute a TellStick Action for device 1
Nov  9 16:10:56 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:10:57 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:10:58 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:10:59 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:10:59 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:00 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:01 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:02 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:02 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:03 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:04 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:05 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:05 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:06 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:07 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:08 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:08 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:09 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:10 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:11 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:12 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:12 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:13 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:14 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:15 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:16 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:16 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:17 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:18 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:19 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:19 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:20 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:21 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:22 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:22 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:23 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:11:24 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:11:25 raspberrypi telldusd: Execute a TellStick Action for device 10

Tdtool -l give me this list which is accurate:

Number of devices: 10
2	Trehodet	ON
3	Hund og vegg	ON
5	TV-hjørnet	ON
6	Bokhyllen	ON
7	Leselampe sofa	ON
10	Lesekrok	ON
1	Nylampe	ON
11	Pistollampen	OFF
14	Stjerner	OFF
15	Dass	OFF

**Comment by larspetter** [comment]
It seems random which devices telldusd loops through...next time the list looked like this from messages as a result on "turn off all lights" command to Siri.

AND importantly - this does not happen each time - just 90% of the times :)

Nov  9 16:19:42 raspberrypi telldusd: Execute a TellStick Action for device 1
Nov  9 16:19:43 raspberrypi telldusd: Execute a TellStick Action for device 3
Nov  9 16:19:44 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:19:45 raspberrypi telldusd: Execute a TellStick Action for device 15
Nov  9 16:19:46 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:19:47 raspberrypi telldusd: Execute a TellStick Action for device 15
Nov  9 16:19:48 raspberrypi telldusd: Execute a TellStick Action for device 2
Nov  9 16:19:48 raspberrypi telldusd: Execute a TellStick Action for device 10
Nov  9 16:19:49 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:19:50 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:19:51 raspberrypi telldusd: Execute a TellStick Action for device 2
Nov  9 16:19:52 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:19:53 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:19:54 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:19:55 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:19:55 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:19:56 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:19:57 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:19:58 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:19:59 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:00 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:01 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:01 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:02 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:03 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:04 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:05 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:06 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:06 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:07 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:08 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:09 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:10 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:11 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:12 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:13 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:13 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:14 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:15 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:16 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:17 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:18 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:19 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:20 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:20 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:21 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:22 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:23 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:24 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:25 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:26 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:27 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:27 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:28 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:29 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:30 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:31 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:32 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:32 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:33 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:34 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:35 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:36 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:37 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:37 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Wed Nov  9 16:21:07 2016 [try http://www.rsyslog.com/e/2007 ]
Nov  9 16:20:38 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:39 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:39 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:40 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:41 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:42 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:43 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:44 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:45 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:45 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:46 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:47 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:48 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:49 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:50 raspberrypi telldusd: Execute a TellStick Action for device 6
Nov  9 16:20:51 raspberrypi telldusd: Execute a TellStick Action for device 5
Nov  9 16:20:52 raspberrypi telldusd: Execute a TellStick Action for device 11
Nov  9 16:20:52 raspberrypi telldusd: Execute a TellStick Action for device 7
Nov  9 16:20:53 raspberrypi telldusd: Execute a TellStick Action for device 6

**Comment by amlinger** [comment]
I don't believe that this is related to this project, but rather to `telldusd` itself. My interpretation of it is that it's unable to send actions to devices successfully. It might be related to [this patch](http://developer.telldus.se/changeset/c3bcd642465801d14a57adf3e44b5303e899353a/telldus-core).

I'll close this for that reason, feel free to continue the discussion of you indeed believe that it is related to this repo.
