### ISSUE TITLE
Can only turn On, not Off

### ISSUE THREAD

**Issue by eripa** [amlinger/homebridge-telldus-tdtool#4]
Seem like the OFF command is lost. All is working fine and I can turn lights on, acknowledged in the log file but nothing happens on OFF commands. Any ideas? 

I'm using these "device" objects (all the same):

```
device {
  id = 1
  name = "Printer"
  controller = 1
  protocol = "arctech"
  model = "selflearning-switch:proove"
  parameters {
    house = "42103842"
    unit = "13"
    code = "0000000000"
    system = "1"
    fade = "false"
  }
}
```

**Comment by amlinger** [comment]
This plugin has only been tested with Nexa selflearning-switches so far, so I do not know how well it will do together with other suppliers, even though the Telldus docs indicates that it should work. 
With that being said, this relies on the command line tool shipped by Telldus, `tdtool`. Turning the lights off from HomeKit should translate into `tdtool --off 1` being issued (for each device). Does that command work for you? I'm just trying to rule out that there is some config/tdtool error here.

**Comment by eripa** [comment]
Thanks for the reply! Yes -- `tdtool --off 1` works fine for me. Also Telldus Live (via TelldusCenter) works fine for all switches. I have the "Proove" self-learning switches.

Is there an easy way to enable some kind of debugging so that I can see if the tdtool is actually being called?

**Comment by amlinger** [comment]
Just glad to see that someone else is using it :)

As of now, there is only a little logging going on to the homebridge log. When you attempt to turn the lights off, an entry that looks something like:

```
[1]: Recieved set state request: false
```

should be written to the log. Is that the case? And does it find all your devices on start-up (should also be in the log)?

Since there are a couple of versions up on `npm`, it might be helpful to verify that you are running the latest version as well.

**Comment by eripa** [comment]
It seems like the issue could actually be with Homebridge. I get the `Recieved set state request: true` on trying a switch the first time, then no reaction on either Off call or trying another switch. If I wait some time it starts working again. So I could be either Homebridge or the Homekit  infrastructure I guess.

To answer your questions; all switches shows up fine in console and in my homekit app. I'm running nodejs/npm v4.2.1/3.8.8

I'll look into Homebridge itself instead. Thanks again for looking into this!

**Comment by amlinger** [comment]
All right!
No problem, hope that you'll sort it out!
