### ISSUE TITLE
Error when using the "sartano" protocol in tellstick.conf

### ISSUE THREAD

**Issue by devit-at** [amlinger/homebridge-telldus-tdtool#44]
i have arctech switches, selflearning dimmers and sartano switches (the ones with dip switches - elro, brennenstuhl, and so on)

when i start homebridge the plugin intializes and runs through my configured devices in /etc/tellstick.conf

the plugin then gives me an error when the config "hits" the first sartano switch:

log:
```
[2017-01-24 14:24:39] [Telldus-TD-Tool] Initializing platform accessory 'Dimmer'...
[2017-01-24 14:24:39] [Telldus-TD-Tool] Initializing platform accessory 'Switch B'...
(node:11745) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'characteristics' of undefined

```
tellstick.conf

```
user = "nobody"
group = "plugdev"
deviceNode = "/dev/tellstick"
ignoreControllerConfirmation = "true"

device {
  id = 21
  name = "Dimmer"
   protocol = "arctech"
  model = "selflearning-dimmer"
  parameters {
    house = "461110"
    unit = "6"
  }
}
device {
  id = 23
  name = "Switch B"
  protocol = "sartano"
  parameters {
    code = "1101101000"
  }
}
```

**Comment by amlinger** [comment]
It might be a problem with the model-field not being present in `tellstick.conf`, since we rely on model to determine what type of Accessory to use. I'm afraid I don't have any possibility of testing myself until the weekend, though.

What does executing `tdtool --list-devices` give you?

**Comment by devit-at** [comment]
hi!
tdtool --list-devices gives me a detailed list with types and ids of all of my devices, even the sartano switches (and they work of course with tdtool -n and tdtool -f)

```
type=device	id=21	name=Dimmer	lastsentcommand=OFF
type=device	id=23	name=Switch B	lastsentcommand=ON
```

i provided you a wrong config for my tellstick, sorry. so here is my correct config:

```
user = "nobody"
group = "plugdev"
deviceNode = "/dev/tellstick"
ignoreControllerConfirmation = "false"

controller {
  id = 1
  # name = ""
  type = 2
  serial = "A501IVXI"
}
device {
  id = 21
  name = "Dimmer"
  controller = 0
  protocol = "arctech"
  model = "selflearning-dimmer"
  parameters {
    house = "231110"
    unit = "6"
  }
}
device {
  id = 23
  name = "Switch B"
  protocol = "sartano"
  parameters {
    code = "1101101000"
  }
}

```

**Comment by amlinger** [comment]
All right, thanks! I'll look into it.

**Comment by devit-at** [comment]
hi there! i looked myself into the code and found 2 things that might be really helpful :)

in telldus-accessory.js i added sartano in homebridgeModel
 ```
var homebridgeModel = {
        // Mapping from Telldus models to Homekit devices. Fetch the actual
        // characteristics and controllerService from the mapping.
        'selflearning-switch': {
          controllerService: new this.Service.Lightbulb(),
          characteristics: [this.Characteristic.On]
        },
        'codeswitch': {
          controllerService: new this.Service.Lightbulb(),
          characteristics: [this.Characteristic.On]
        },
        **'sartano': {
          controllerService: new this.Service.Lightbulb(),
          characteristics: [this.Characteristic.On]
        },**
        'selflearning-dimmer': {
          controllerService: new this.Service.Lightbulb(),
          characteristics: [this.Characteristic.On, this.Characteristic.Brightness]
        }
      }[this.model];
```

in addition - there is a crucial key missing in telldus.conf (which is btw not needed for telldusd to work)
i recognized that the telldus-accessory.js is checking for "model". sartano switches don't have or need this key - and that's why it's not working.

so i added this to my tellstick.conf

```
device {
  id = 23
  name = "Switch B"
  **model = "sartano"**
  protocol = "sartano"
  parameters {
    code = "1101101000"
  }
}
```

and - tadaaa it works ! ;)
