### ISSUE TITLE
No devices found on windows

### ISSUE THREAD

**Issue by gustafnilklint** [amlinger/homebridge-telldus-tdtool#49]
I have set up homebridge to run on my Windows 7 machine.
I have Telldus Center installed and have a few devices configured. If I run TDTool in terminal it lists my devices, but when initialising in homebridge it never finds any.
Any advice is appreciated!

**Comment by amlinger** [comment]
Hi @gustafnilklint!

Interesting, as I have no Windows machine easily accessible for me, it'll be hard to test. Could you add some context in the form of logs, that might be helpful in debugging this (The output of `tdtool --list-devices` would also be useful). 

Also, make sure that `tdtool --list-devices` provides a list of devices _before_ you initialise Homebridge, as devices are only detected on startup (see https://github.com/amlinger/homebridge-telldus-tdtool/issues/48).

**Comment by nklint** [comment]
The logs from Homebridge contains no error or warnings. Quite similar to issue #43 . But with the key difference that it’s not even working when I run Homebridge manually.
TDTool lists all my devices and is able to switch on and off. And yes this is verified before I try to launch Homebridge.

I can assist (hopefully) if you want me to test something specific. But I sort of gave up on it.. And instead I set up a raspberry pi to host the TellStick and Homebridge instead.
Unfortunately I have some minor issues there too 😩 in separate topic.

**Comment by amlinger** [comment]
If you pursue this any further, let me know, it would be interesting seeing how this runs on Windows :)
