### ISSUE TITLE
My temperaturehumidity device show up as "not answering"

### ISSUE THREAD

**Issue by nklint** [amlinger/homebridge-telldus-tdtool#51]
I have a single temperaturehumidity sensor. Well it's actually a dual device with and indoor  temperaturehumidity sensor and a white cable that you're supposed to hang out your window and a separate temperature sensor for the outdoor temp. (The brand is Proove)
As you can see it is listed in `tdtool -l` it has temperature readings.

```
SENSORS:

PROTOCOL            	MODEL               	ID   	TEMP 	HUMIDITY	RAIN                	WIND                	LAST UPDATED        
fineoffset          	temperaturehumidity 	135  	8.3°	67%     	                    	                    	2017-10-10 09:18:00 
fineoffset          	temperature         	136  	162.4°	        	                    	                    	2017-10-10 09:18:05 
```

My homebridge config is like this:
```
{
  	"platform" : "Telldus-TD-Tool",
  	"name" : "Telldus-TD-Tool",
  	"sensors" : [{
    	    "id": "135",
    	    "name": "Uterum",
    	    "model": "temperaturehumidity",
    	    "maxAge": 120
  	}]
    }
```
I have not seen a single temperature reading inside homekit, but it works all the time with tdtool from commandline

**Comment by nklint** [comment]
Ok an update on this issue.
It seems that removing the sensor from the config-file makes the sensor show up in homebridge.
Unfortunately this means that i automatically get all sensors in homebridge. So now both "id 135" (temperaturehumidity) and "id 136" (temperature) show up.

Is this the intensional functionality? I might have misinterpreted the instructions for sensors?

**Comment by amlinger** [comment]
By default, all sensors are shown in Homebridge, only if the sensors field is used, it will act as a filter. 

I'm curious why it is not updating, I suspect that it does not find the sensor, meaning that this condition is not satisfied:
```js
  sensor: id => TDtool.listSensors().then(
    sensors => sensors.find(s => s.id === id)),
```
from https://github.com/amlinger/homebridge-telldus-tdtool/blob/master/src/lib/tdtool.js#L59-L60

If you have logs, that would be helpful as well, all though I might be able to reproduce with what you've provided already.

**Comment by ihatetoregister** [comment]
I've got the same issue and this is what I've found. 

I have the following sensors:

```
SENSORS:

PROTOCOL      MODEL                 ID      TEMP    HUMIDITY    RAIN   WIND   LAST UPDATED
fineoffset    temperaturehumidity   167     20.6°   34%                       2017-10-31 15:44:32
fineoffset    temperaturehumidity   228     8.0°    255%                      2017-10-31 15:16:21
```

Running with the following configuration (sensors included) then they are reported as undefined (see log)
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "",

  "accessories": [
  ],

  "platforms": [
    {
      "platform" : "Telldus-TD-Tool",
      "name" : "Telldus-TD-Tool",
      "sensors" : [{
        "id": "228",
        "name": "Terass",
        "model": "temperature",
        "maxAge": 3600
      },{
        "id": "167",
        "name": "Arbetsbod",
        "model": "temperaturehumidity",
        "maxAge": 3600
      }]
    }
  ]
}
```
However, removing the sensors in the configuration makes the sensor report values.

Logfile (sensors not working)
https://gist.github.com/ihatetoregister/213c76b7e0fea1052093839eb70c76b6

Logfile (sensors working)
https://gist.github.com/ihatetoregister/6161616a2405a70fbd3be08bd83233a4

**Comment by amlinger** [comment]
Sorry for the very late (borderline extreme) turnaround on this.

One thing that might help with issues like these is refreshing Homebridge, by stopping the service, removing the `persist/` folder (for me found in `/var/homebridge/`), and starting the service again. On occasion the cache there might end up in a strange state, such as it did for me very recently, which is why I came to think of this.

Let me know if this might help.

I've setup https://github.com/amlinger/homebridge-telldus-tdtool/pull/53/ to provide additional logging around tdtool interactions to see where something might go wrong.

**Comment by ciryon** [comment]
I have the same issue here when filtering sensors.

**Comment by ciryon** [comment]
Tried to remove Homebridge cache but still no go. :(

**Comment by nklint** [comment]
I have resolved the mystery around the failing sensors!

It's actually only the instructions that is incorrect regarding the format of the config.

```
"sensors" : [{
        "id": 228,
        "name": "Terass",
        "model": "temperature",
        "maxAge": 3600
      }
```
Remove the quotation-marks around the actual id of your sensor and it's good to go!
The id should be specified as an integer.
