### ISSUE TITLE
Setting up Devices

### ISSUE THREAD

**Issue by jamesbryer** [amlinger/homebridge-telldus-tdtool#52]
Hi, 
I'd like to prefix this with the fact I do not know any coding/programming languages and am amazed I have got this far. This is completely new ground to me. Please put anything in lay-mans terms for I have very little idea on what I'm doing :) 

I have installed homebridge, the telldus-td-tool and tellstick.conf-parser (that is all, apart from editing the config.json adding the Telldus tool in the platforms as advised in the guide) and when I run homebridge I get an error after it starts attempting to load devices(I will paste error message at  the bottom of here). I assume this is because I have no devices set up (duh). I don't have Telldus core (I genuinely cannot find a single working download for it) but I do have the Telldus centre with the devices (self learning switches from homeeasy) I want to run. I believe telldus core is included in the installation of telldus centre. Would anyone be able to guide me on how to set up these devices? I assume I need to add to the telldus-accessory.js file. Any help would be very much appreciated :) 

Error message:
DeprecationWarning: sys is deprecated. Use util instead.
/usr/local/lib/node_modules/homebridge-telldus-tdtool/node_modules/tellstick.conf-parser/dist/index.js:116
        resolve(Parser.parseString(buffer.toString()));
                                          ^

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-telldus-tdtool/node_modules/tellstick.conf-parser/dist/index.js:116:43)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by amlinger** [comment]
Hi @jamesbryer,

It would help with some context of how your environment is setup. What type of machine/OS are you running on, is it a RasberryPi, a MacBook or something else?

Whether `telldus-core` is installed and has brought `tdtool` along with it on your setup should be verifiable by typing
```
tdtool --list-devices
```
and seeing that it gives an output of the devices connected to your Tellstick.

A way to get telldus-core running on a Debian-based system (such as Raspian on a RaspberryPi) using the apt package manager is described [here](https://lassesunix.wordpress.com/2013/08/12/installing-telldus-core-on-raspberry-pi/) (see steps 1-3), and involves compiling and installing from source.

To your specific error, it seems come from [these lines](https://github.com/amlinger/tellstick.conf-parser/blob/master/src/index.js#L124-L128).

What it indicates is that the configuration file for Tellstick is missing (the error message should have been more clear, I will attempt to address that).

This plugin expects there to be a file in the `/etc/` directory on your system, called `tellstick.conf` (full path `/etc/tellstick.conf`). `tdtool` expects the file to be there as well to be able to communicate with devices. Documentation for how to format this file can be found [here](https://developer.telldus.com/wiki/TellStick_conf), and [here](https://gist.github.com/amlinger/ec682959e4c54a10abe47097e3e982df) is a sample of how my file looks.

I hope this helps, please provide an update how this works out for you.

**Comment by amlinger** [comment]
I've created a new code change in https://github.com/amlinger/homebridge-telldus-tdtool/pull/53 that will likely help with figuring out whether tdtool is on the system or not. I'll look into setting up more logging for the existence of the `tellstick.conf` file as well.

**Comment by jamesbryer** [comment]
Hi, thanks so much for your quick response. 
For reference I am running it on my MacBook Pro running High Sierra (my last choice of machine behind my windows server and my raspberry pi 3)
I have tried using the apt package manager and installing from source (for raspberry pi), however in the past few weeks the source appears to have gone and the apt-get commands say the sources don't exist. Telldus have appeared to be shutting down support for older devices... 

Running tdtool --list-devices does show my device (hoorah) 

I have edited and placed the tellstick.conf file into the /etc/ folder and this is what it looks like 

device {
  id = 1
  name = "Plug"
  protocol = "arctech"
  model = "selflearning-switch"
  parameters {
    house = "100010"
    unit = "1"
  }
}

user = "nobody"
group = "plugdev"
deviceNode = "/dev/tellstick"
ignoreControllerConfirmation = "false"
controller {
  id = 4
  type = 2
  serial = "A703AJQB"
}

I was unsure what to enter in the "house" field and also what the bottom section under the device means. When I use 'Go to Folder' in Finder "/dev/" doesn't show up (devicenode = /dev/tellstick), is each "serial" different for each device/homebridge installation? 

Anyhow Homebridge will now run however in the Home app when scanning the code I get error 'Couldn't add accessory'. When initially setting up the .conf file I first did an attempt which didn't find device but Homebridge DID still run showing the QR code. This added to homebridge fine but once Homebridge found the device (plug) in the updated .conf file it refused to add to the Home app in iOS. I'm not 100% sure but homebridge does appear to pick up my device (named "plug"). I have tried deleting the 'persist' file in homebridge folder yielding the same results. Here is the entire start up sequence for Homebridge:

Jamess-MacBook-Pro:~ James$ homebridge
[2018-2-10 23:35:00] Loaded plugin: homebridge-script2
[2018-2-10 23:35:01] Registering accessory 'homebridge-script2.Script2'
[2018-2-10 23:35:01] ---
[2018-2-10 23:35:01] Loaded plugin: homebridge-telldus-tdtool
[2018-2-10 23:35:01] Registering platform 'homebridge-telldus-tdtool.Telldus-TD-Tool'
[2018-2-10 23:35:01] ---
[2018-2-10 23:35:01] Loaded config.json with 0 accessories and 1 platforms.
[2018-2-10 23:35:01] ---
[2018-2-10 23:35:01] Loading 1 platforms...
[2018-2-10 23:35:01] [Telldus-TD-Tool] Initializing Telldus-TD-Tool platform...
[2018-2-10 23:35:01] [Telldus-TD-Tool] Loading devices...
(node:27340) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
[2018-2-10 23:35:02] [Telldus-TD-Tool] Found 1 item of type "device" from "tdtool --list-devices".
[2018-2-10 23:35:03] [Telldus-TD-Tool] Found no items of type "sensor" from "tdtool --list-sensors".
[2018-2-10 23:35:03] [Telldus-TD-Tool] Initializing platform accessory 'Plug'...
[2018-2-10 23:35:03] [Telldus-TD-Tool] [Plug]: getServices called
Setup Payload:
X-HM://0023ISYWYM48I
Scan this code with your HomeKit app on your iOS device to pair with Homebridge: 

As you can see I still get the Deprecation warning (I do not know what this means but most warnings are bad right?) 

Thank you so much for your help, I am determined to get this working! 

-James

**Comment by jamesbryer** [comment]
UPDATE:

I got it working!! I found that another instance of homebridge was in the "default room' in the Home app. After deleting this the Plug is found and IS functional!! Thank you so much for your help. Now I know how to get this working I will attempt to set up on my Windows server and if that still wont work I will try again (for probably the 5th of 6th time) installing telldus-core or telldus centre on the raspberry pi 

again thank you so much, your plugin seems awesome and this has really opened my eyes to how fun programming is and you've inspired me to try and actually learn this. Ya'll are very talented :)

**Comment by amlinger** [comment]
As far as I've been able to tell, the `id`, `model` and `protocol` fields are really what tdtool cares about. The documentation for how to format the file can [be found here](https://developer.telldus.com/wiki/TellStick_conf), but it doesn't cover it very thoroughly but only describes the allowed ranges for the parameters.

I'm glad you got it working, happy to help!

I'll close this for now as it seems that your issue is resolved.
