### ISSUE TITLE
Implement Shutter device support

### ISSUE THREAD

**Issue by zobi** [amlinger/homebridge-telldus-tdtool#6]
My shutter is recognize like a light.
We can't set the characteristic of each device.

**Comment by amlinger** [comment]
Hi Zoby,

I'm not sure that I follow, what kind of a device are you trying to set up, and which characteristics should it be capable of?

**Comment by zobi** [comment]
I use 2 type of device with tdtool : light and shutter
In homekit the shutter is show like a light and not a shutter.
Most important in siri i must say : "Allume le volet" like a light but we should say "Ouvre le volet"

**Comment by amlinger** [comment]
You are correct, this is not implemented yet, only lights are currently supported. I will most likely not be able to get around to fixing this in the next couple of weeks, but feel free to give it a go yourself. I'll be happy to provide you with some pointers as to where you could get started.

A crucial part is that your actions are supported by Telldus CLI tool tdtool; Is your device-manufacturer in [this list](http://developer.telldus.com/wiki/TellStick_conf), and what protocol should it be supported by?

**Comment by zobi** [comment]
For sure it works with td tool. 
for exemple : tdtool --on 3 => open the shutter in my kitchen ;) 
It's intertechno module who is in the list of supported device :p 
Thanks again for your help

**Comment by amlinger** [comment]
All right, then it should not be a problem to implement this in this plugin as well :)

**Comment by zobi** [comment]
Great news ;) 
An other problem, but i don't know if it's my configuration or the plugin.
When I tell to Siri (same in official apps) switch on the light : command is understand and the light switch on, but Siri seem to wait a feedback. In official app same problem apps wait and I have to shutdown the apps to do another command. Do you know this issue ?

**Comment by amlinger** [comment]
As far as I know, no feedback is sent for when a light is actually turned on, at least not via this plugin, and I guess one would have to consult the Homekit protocol, as well as Homebridge's source code to find out how that could be achieved with your (or any Telldus) setup :)

**Comment by zobi** [comment]
In telldus-accessory.js file :

If I change :
`callback(null, out.endswith('Success'));`
By `callback(null);`
It works ! Siri did not wait and official apps works too ;) 
But I don't know what callback means really ....

**Comment by amlinger** [comment]
I believe that [this](https://github.com/nfarina/homebridge/blob/620c8473b86fe21fe473b18894e6ca592caeb13b/lib/bridgeSetupManager.js#L52-L62) is why Siri does not wait when omitting the callback parameters. I will have a look in the next couple of days, and have opened #7 for that issue instead.

Thanks @zobi for pointing that out! :)

**Comment by amlinger** [comment]
Closing this as it seems as #7 took care of it.
